dnd-side-project/dnd-10th-8-android

- .github/CODEOWNERS
- CODEOWNERS
- CODEOWNERS 가 정상작동하지 않아 수정했습니다.
-
> [System] Assigner 등록

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/AuthenticationApi.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/BookkeepingApi.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/base/BaseActivity.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/base/BaseViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/ComposeUtil.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/coroutine/CoroutineUtil.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/ApplicationState.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainActivity.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/bookkeeping/BookkeepingScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/LoginNavGraph.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/LoginScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
- CoroutineErrorHandler 을 적용시켰습니다.
- LaunchedEffectWithLifecycle Util 을 만들었습니다.
- 그 외 자잘한 오류를 수정했습니다.
-
> [System] Error Handling 고도화

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/BottomSheetScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/ConfirmButton.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/DialogScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
- presentation/src/main/res/values/strings.xml
- BottomSheetScreen 을 수정했습니다. (Round Corner 만 추가하도록 설정)
> [Setting] BottomSheetScreen 고도화

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/MainScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/RegistrationConstant.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/RegistrationNavGraph.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/RegistrationViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingConstant.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingState.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/collecting/RegistrationCollectingViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingConstant.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingState.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/naming/RegistrationNamingViewModel.kt
- RegistrationNavGraph를 생성하였습니다.
- RegistrationNamingScreen과 RegistrationNamingDestination을 구현하였습니다.
- RegistrationCollectingScreen과 RegistrationCollectingDestination을 구현하였습니다.
- Preview 생성하여 ui 테스트 진행하였습니다.
-
> [Feature] RegistrationNavGraph & RegistrationDestination 만들기

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/CustomTextField.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
- presentation/src/main/res/values/strings.xml
-  커스텀 가능한 BasicTextfield 구현하였습니다.
> [Setting] BasicTextField Component 구현

- app/src/main/res/values/strings.xml
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashViewModel.kt
- presentation/src/main/res/values/strings.xml
- SplashScreen 을 Convention 에 맞게 수정했습니다.
-
> [Refactoring] Splash Screen Migration

- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/authentication/RegistrationUseCase.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/onboarding/LoginOnBoardingViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainConstant.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainErrorType.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/component/ErrorUserNamingComponent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/component/RegistraionUserDate.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/type/RegistrationMainNamingErrorType.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/type/UserGender.kt
- presentation/src/main/res/drawable/ic_check_circle.xml
- presentation/src/main/res/drawable/ic_close_circle.xml
- presentation/src/main/res/values/strings.xml
- Registration ui 구현하였습니다.
- use case 생성하여 기능 적용하였습니다.
- login - onBoarding - registration 플로우 적용하였습니다.
Screen_recording_20240131_042528.webm
> [Feature] RegistrationScreen UI 로직 구현

- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/member/AddGroupUseCase.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupState.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/group/AddGroupViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/event/common/relation/SearchRelationScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
- 경조사 그룹 추가 BottomSheet 를 만들었습니다.
- 아직 Test 안해봄. 넣기 전에 테스트 완료하고 넣도록 하겠습니다.
> [Feature] 경조사 그룹 추가 BottomSheet

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/di/RepositoryModule.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/FileApi.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/file/GetPreSignedUrlRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/file/MockFileRepository.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/file/RealFileRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/file/PreSignedUrl.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/FileRepository.kt
> [Feature] PreSigned 관련 API / Repository 연결

- app/src/main/kotlin/ac/dnd/bookkeeping/android/BookkeepingApplication.kt
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/Constants.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/NotificationUtil.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
- NotificationUtil 을 만들었습니다.
- 이후 연동해서 알람 등록 기능 만들어보겠습니다.
-
> [Setting] NotificationUtil

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/ComposeUtil.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/DialogScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/setting/SettingScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/registration/main/RegistrationMainScreen.kt
> [Setting] DialogScreen isShowing 제거

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/FileApi.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/authentication/LoginRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/authentication/RegisterRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/AddHeartRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/AddUnrecordedHeartRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/heart/GetHeartListRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/relation/AddRelationRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/AddScheduleRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/util/NetworkUtil.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/authentication/sociallogin/KakaoLoginRepositoryImpl.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/heart/MockHeartRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/heart/Heart.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/heart/RelatedHeart.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/relation/RelationDetail.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/relation/RelationSimple.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/schedule/UnrecordedSchedule.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/GroupChipListComponent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingPriceField.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/main/detail/HistoryDetailScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/login/main/LoginMainScreen.kt
- API 변경에 따른 model 변경입니다.
- https://www.notion.so/ERD-API-bdcbf823c85e4e4c9593da878cbcea94
> [Feature] 마음 조회하기 Response Model 변경

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/relation/GetRelationRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/relation/MockRelationRepository.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/relation/RealRelationRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/relation/RelationDetailWithUserInfo.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/RelationRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/GetRelationUseCase.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationScreen.kt
- RelationDetailWithUserInfo 모델 추가하여 api 수정하였습니다. 
- 관계 정보 구현하였습니다.
-
> [Feature] 관계 정보 구현

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryDetailGrowthType.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthConstant.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthScreen.kt
> [Feature] 성장 단계 레벨 구현

- gradle/libs.versions.toml
- presentation/build.gradle.kts
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarConfig.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarPicker.kt
- 라이브러리 추가해서 month selector 기능구현하였습니다.
- 디자인도 적용했습미다.(공통)
-
> [Setting] month selector 구현

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/expansion/Text.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryDetailSortedType.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailViewModel.kt
- presentation/src/main/res/drawable/board.xml
> [Feature]: 경조사비 내역 상세 page 구현

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/coroutine/event/MutableEventFlow.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/model/history/HistoryEventType.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedState.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedViewModel.kt
- presentation/src/main/res/drawable/ic_unrecorded_flower.xml
- 기록되지 않은 일정 구현하였습니다.
- 요거 api 수정 & 추가로 나와야해서 onskip은 일단 그냥 넘기는걸로 적용했습니다.
> [Feature] 기록되지 않은 일정 구현 

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/ScheduleApi.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/GetAlarmListRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/GetScheduleListRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/MockScheduleRepository.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/RealScheduleRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/schedule/Alarm.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/schedule/AlarmRepeatType.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/schedule/Schedule.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/ScheduleRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/GetAlarmListUseCase.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/GetScheduleListUseCase.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedDestination.kt
- Schedule API 를 업데이트했습니다. (nullable 처리, Group 관련, 새로운 API 등...)
-
> [Feature] Schedule API 업데이트

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/TimePicker.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/TimePickerType.kt
> [Feature]: time picker 구현

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingPriceField.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/calendar/HistoryCalendarScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationViewModel.kt
- 마음 등록하기 디자인 수정 & 구체화 하였습니다.
-
> [Feature]: 마음 등록하기 구체화

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/textfield/TypingTextField.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
- 텍스트 필드 디자인에 맞게 수정했습니다.
- 사용 방식에 변경사항은 없습니다.
-
> [Setting]: TextField 스타일 적용

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/component/FieldSelectComponent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/event/EventTypeScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailConstant.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditViewModel.kt
- presentation/src/main/res/drawable/ic_alert_triangle_gray.xml
- 내역 정보 수정 구체화하였습니다.
- 각 destination 연결하였습니다.
-
> [Feature]: 내역 정보 수정 구체화

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/alarm/AlarmReceiver.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/alarm/AlarmUtil.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/alarm/NotificationUtil.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/test/TestScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/splash/SplashViewModel.kt
- BroadCastRecevier 등록까지 완료했습니다.
- 반복기능은 제외했습니다.
> [Feature] 알람 구현

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/CalendarPicker.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chart/stick/StickChart.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chart/stick/StickChartData.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/chip/ChipItem.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/StatisticsScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/statistics/user/StatisticsUserScreen.kt
> [Feature] Statistics 화면 디자인 검수

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/get/GetRelationScreen.kt
- presentation/src/main/res/drawable/ic_check_circle_gray.xml
- 이름 선택 구체화 & 디자인 검수하였습니다.
- relation destination 등록하였습니다.
-
> [Feature]: 이름 선택 구체화 & 디자인 검수

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/GetGroupIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/GetGroupViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/test/TestScreen.kt
- 그룹 선택 기능을 구체화하고 디자인 검수하였습니다.
-
> [Feature]: 그룹 선택 구체화 & 디자인 검수

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/ScheduleApi.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/api/StatisticsApi.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/authentication/LoginRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/EditScheduleReq.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/GetScheduleRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/MockScheduleRepository.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/RealScheduleRepository.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/member/MockMemberRepository.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/member/RealMemberRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/schedule/Schedule.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/MemberRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/repository/ScheduleRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/EditScheduleUseCase.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/member/GetProfileUseCase.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenHeader.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenItem.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddViewModel.kt
- API 스펙 업데이트했습니다.
- https://dnd-10th-8-be.slack.com/archives/C06F0UWR81K/p1708062218890699
> [Feature] API 스펙 업데이트

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/GetScheduleListRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/schedule/GetScheduleRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/schedule/MockScheduleRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/feature/schedule/Schedule.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/schedule/GetScheduleUseCase.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/TimePicker.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenHeader.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenItem.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddViewModel.kt
- Schedule 화면 수정했습니다.
- Schedule List 에서는 alarm, repeat 정보가 내려오지 않아 null 처리 했습니다.
- TimePicker 특정 시간대 수정이 필요합니다.
-
> [Feature] Schedule 화면 디자인 검수

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/feature/relation/KakaoFriendRepositoryImpl.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/usecase/feature/relation/AddRelationWithUploadUseCase.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/GalleryScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/common/gallery/GalleryViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationConstant.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/relation/RelationViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/growth/HistoryDetailGrowthConstant.kt
- presentation/src/main/res/drawable/ic_default_user_image.xml
- presentation/src/main/res/drawable/ic_gift_activate.xml
- presentation/src/main/res/drawable/ic_gift_disabled.xml
- presentation/src/main/res/drawable/ic_polygon.xml
- 관계 등록 구체화 & 디자인 검수 하였습니다.
- addFloating 버튼 추가하고 각 뷰 연결하였습니다.
- 갤러리, 그룹 디자인 오류 있어서 테스트하면서 같이 수정했습니다.
- AddRelationWithUploadUseCase 추가하였습니다.
-
> [Feature]: 관계 등록 구체화 & 디자인 검수

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/member/GetProfileRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/member/MockMemberRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/member/Profile.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/HomeDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageState.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawConstant.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawEvent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawIntent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawState.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawViewModel.kt
- 마이페이지 & 계정 삭제 ui 구현하였습니다.
- 마이페이지 기능 구체화하였습니다.
- 로그아웃 & 계정 삭제 기능 구현 하였습니다.
- 프로필 수정은 로그인 검수 후 진행하겠습니다.
> [Feature] 마이페이지 구현

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/network/model/member/GetProfileRes.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/repository/member/MockMemberRepository.kt
- domain/src/main/kotlin/ac/dnd/bookkeeping/android/domain/model/member/Profile.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageViewModel.kt
> [Fix] 빌드 오류 해결

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/HistoryViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/detail/information/HistoryDetailInformationScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/registration/HistoryRegistrationDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedDestination.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedViewModel.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/mypage/MyPageScreen.kt
- 히스토리 관련 된 모든 ui 검수 & 기능 적용하였습니다.
- 네비게이션 연결하여 기능테스트 하였습니다.
- 기능 오류 수정하였습니다.
-
> [Feature]: History 구체화 & 디자인 검수

- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/util/alarm/AlarmUtil.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/common/view/calendar/TimePicker.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/common/notification/NotificationScreen.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/ScheduleScreenItem.kt
- presentation/src/main/kotlin/ac/dnd/bookkeeping/android/presentation/ui/main/home/schedule/add/ScheduleAddScreen.kt
- 오류 수정했습니다.
- https://ko.wikipedia.org/wiki/24%EC%8B%9C%EA%B0%84%EC%A0%9C 기준으로 시간 테스트 했습니다
> [Setting]: Time Picker 오류 수정

- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/database/BookKeepingDatabase.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/database/sample/SampleDao.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/database/sample/SampleEntity.kt
- data/src/main/kotlin/ac/dnd/bookkeeping/android/data/remote/local/di/LocalModule.kt
-  Room DB 적용했습니다. Exposed 안함!
-
> [Setting] Room DB 적용

- data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/environment/BaseUrlProvider.kt
> [Setting] Base URL 적용

- .github/workflows/android.yml
- .gitignore
- app/build.gradle.kts
- app/src/main/kotlin/ac/dnd/mour/android/MourApplication.kt
- build.gradle.kts
- common/build.gradle.kts
- data/build.gradle.kts
- domain/build.gradle.kts
- domain/src/main/kotlin/ac/dnd/mour/android/domain/usecase/authentication/LoginUseCase.kt
- gradle/libs.versions.toml
- presentation/build.gradle.kts
- 사용법 : Firebase.analytics.logEvent()
- google-service.json 이 필요합니다. 아래 링크에서 받을 수 있습니다.
- https://console.firebase.google.com/u/4/project/mour-f7696/settings/general/android:ac.dnd.mour.android
-
> [Setting] Firebase 적용

- app/build.gradle.kts
- build.gradle.kts
- data/build.gradle.kts
- domain/build.gradle.kts
- gradle/libs.versions.toml
- presentation/build.gradle.kts
- 죄송합니다.. 튕기네요.. 동작확인 완료했습니다.
-
> [Fix] Firebase Plugin Fix

- app/build.gradle.kts
- app/src/main/kotlin/ac/dnd/mour/android/MourApplication.kt
- data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/MockAuthenticationRepository.kt
- data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/RealAuthenticationRepository.kt
- domain/src/main/kotlin/ac/dnd/mour/android/domain/repository/AuthenticationRepository.kt
- gradle/libs.versions.toml
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/invalid/InvalidJwtTokenActivity.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/invalid/InvalidJwtTokenViewModel.kt
- presentation/src/main/res/values/strings.xml
- 기존 Refresh Token 이 만료되었을때 처리하지 않던 현상을 해결했습니다.
-
> [System] Invalid Token 체크

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/notification/NotificationScreen.kt
- Notification Screen QA 사항 적용했습니다
-
> [Feature] Notification Screen QA

- data/src/main/kotlin/ac/dnd/mour/android/data/repository/feature/statistics/MockStatisticsRepository.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/chart/stick/StickChart.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/chip/ChipItem.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/segment/SegmentControl.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/model/history/HistoryEventType.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/StatisticsMeScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/me/event/StatisticsMeEventScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/user/StatisticsUserScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/statistics/user/group/StatisticsUserGroupScreen.kt
> [Feature] Statistics QA

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/model/mypage/ProfileModel.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageDestination.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileConstant.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileDestination.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileEvent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileIntent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileModel.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileState.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileViewModel.kt
> [Feature]: 마이페이지 수정 구현

- data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/environment/BaseUrlProvider.kt
- presentation/src/main/AndroidManifest.xml
> [Setting] 서버 연결

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/component/FieldSubjectComponent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingTextField.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationScreen.kt
- presentation/src/main/res/drawable/ic_history_edit.xml
> [Feature]: 관계 & 카카오톡 등록 QA

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/PriceChipComponent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingPriceField.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
> [Feature]: 그룹 선택 & 마음 등록 QA

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/component/FieldSelectComponent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/unrecorded/HistoryUnrecordedPageScreen.kt
- presentation/src/main/res/drawable/ic_text_field_chevron_right.xml
> [Feature] 지난 일정 기록 & 등록된 내역 수정 디자인 QA

- data/src/main/kotlin/ac/dnd/mour/android/data/repository/authentication/sociallogin/KakaoLoginRepositoryImpl.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/DialogScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawScreen.kt
> [Feature] 카카오 로그인 수정 & 마이페이지 QA

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailPageScreen.kt
- presentation/src/main/res/drawable/ic_close_circle_white.xml
- presentation/src/main/res/drawable/ic_search_history.xml
> [Feature]: 히스토리 1차 & 2차 디자인 QA 적용

- data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/environment/ErrorMessageMapper.kt
- data/src/main/res/values/errors.xml
> [Feature] 에러 메세지 처리

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingTextField.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/get/GetRelationScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/edit/HistoryDetailEditScreen.kt
> [Feature]: 이름 선택 디자인 수정 & 내역 상세 디자인 QA

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailScreen.kt
> [Fix] 내역 수정

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/component/FieldSelectComponent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/view/textfield/TypingTextField.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeConstant.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeDestination.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/HomeViewModel.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupIntent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupViewModel.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationIntent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationViewModel.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryBackgroundComponent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryRelationItem.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/detail/HistoryDetailItem.kt
> [Feature] MA01,MA03 기능 & 디자인 QA

- data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/TokenApi.kt
> [Fix] Refresh Token Fix

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageIntent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/MyPageViewModel.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileEvent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileIntent.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/profile/MyPageProfileViewModel.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/mypage/setting/withdraw/MyPageSettingWithdrawScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/login/main/LoginMainScreen.kt
- presentation/src/main/res/drawable/ic_kakao_logo.xml
> [Feature] LO00 디자인 & 기능 QA

- data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/FileApi.kt
> [Fix] S3 File Upload Method Fix

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/common/util/logevent/LogEventUtil.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/add/AddGroupScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/edit/EditGroupScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/group/get/GetGroupScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/RelationScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/common/relation/get/GetRelationScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryPageScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/HistoryScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/history/registration/HistoryRegistrationScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/login/main/LoginMainScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/login/onboarding/LoginOnBoardingScreen.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/registration/main/RegistrationMainDestination.kt
- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/registration/main/RegistrationMainScreen.kt
> [Feature] 이벤트 로그 등록

- presentation/src/main/kotlin/ac/dnd/mour/android/presentation/ui/main/home/schedule/ScheduleScreen.kt
> [Fix] 일정 변경 안되는 오류 수정

- data/src/main/kotlin/ac/dnd/mour/android/data/remote/network/api/FileApi.kt
> [Fix] S3 Content Type

- gradle/libs.versions.toml
> [Setting] Version Update

- app/proguard-rules.pro
> [Fix] KakaoTalk Proguard Rule Fix

- gradle/libs.versions.toml
> [Version] Version 1.0.1

- app/proguard-rules.pro
> [Fix] Retrofit Proguard Rule Fix
